[package]
name = "eyeballs"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "0.3.0-alpha.17", features = ["nightly", "async-await"] }
async-std = "0.99.3"
rand = "0.7.0"
lazy_static = "1.3.0"
