[package]
name = "eyeballs"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.17"
tokio = "0.2.0-alpha.1"
tokio-timer = "0.3.0-alpha.1"
rand = "0.7.0"
